name: Build for testing

on:
  workflow_dispatch:
  push:
    branches:
    - "test"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install build dependencies
      run: sudo apt-get install --assume-yes gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libcrypto++-dev libgnutls28-dev uuid-dev

    - name: Download source code
      run: |
        git clone --branch test --depth 1 https://github.com/bschnei/ebu-bootloader.git .
        git submodule sync
        git -c protocol.version=2 submodule update --init --force --depth=1

    - name: Build
      run: make

    - name: Save image to artifacts
      uses: actions/upload-artifact@v4
      with:
        path: trusted-firmware-a/build/a3700/release/flash-image.bin
